version: '3'
services:
  angular-app:
    build:
      context: .
      docker-file: Dockerfile
      ports:
        - "8080:80"
      volumes:
        - .:/app
      environments:
        - NODE_ENV=production
